version: '3'

services:
  db_consultorio:
    image: mysql:5.7
    container_name: db_consultorio
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: consultorio
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
